[theme]
theme = "plain"

[theme.overrides]
idle_bg = "#161616"
idle_fg = "#dde1e6"
info_bg = "#78a9ff"
info_fg = "#161616"
good_bg = "#78a9ff"
good_fg = "#161616"
warning_bg = "#ff7eb6"
warning_fg = "#dde1e6"
critical_bg = "#ee5396"
critical_fg = "#dde1e6"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"

[icons]
icons = "awesome6"

#[[block]]
#block = "service_status"
#service = "ollama"
#active_format = " ollama running "
##inactive_format = " ollama off "
#[block.theme_overrides]
#idle_bg = "#ee5396"
#idle_fg = "#dde1e6"

#[[block]]
#block = "docker"
#interval = 2
#socket_path = "/run/user/1000/podman/podman.sock"
#format = " $icon $running/$total images: $images "
#[block.theme_overrides]
#idle_bg = "#be95ff"
#idle_fg = "#161616"
[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
good = 40
idle = 60
info = 80
interval = 10
warning = 90
chip = "coretemp-isa-*"

[[block]]
block = "custom"
command = '''printf '\u26ED ' ; cat /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon5/fan1_input '''
interval = 5

[[block]]
block = "custom"
command = '''printf '\u26ED ' ; cat /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon5/fan2_input'''
interval = 5

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
[block.theme_overrides]
idle_bg = "#78a9ff"
idle_fg = "#161616"

[[block]]
block = "memory"
format = " $icon $mem_avail.eng(prefix:M)/$mem_total.eng(prefix:M) "
[block.theme_overrides]
idle_bg = "#08bdba"
idle_fg = "#161616"

[[block]]
block = "cpu"
interval = 1
[block.theme_overrides]
idle_bg = "#3dddb9"
idle_fg = "#161616"

[[block]]
block = "sound"
[block.theme_overrides]
idle_bg = "#33b1ff"
idle_fg = "#161616"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%h %d %I:%M %p', l:en_US) " # Mon day w/12H
short = " $icon $timestamp.datetime(f:'%a %FT%T', l:en_US) "      # DoW y-m-d w/24H


[[block]]
block = "time"
interval = 5
timezone = "UTC"
[block.format]
full = " $icon UTC:$timestamp.datetime(f:'%R', l:en_US) "        # month-day w/ 24H
short = " $icon UTC:$timestamp.datetime(f:'%a %FT%T', l:en_US) " # DoW y-m-d w/24H

[[block]]
block = "battery"
driver = "sysfs"
interval = 10
#format = "{percentage}% {time}"
